import CardCode from "../../components/cardCode";
function pwa() {
  return (
    <div className="container mx-auto p-4">
      <h1 className="text-3xl font-bold mb-4">React setup docs</h1>

      <div className="mb-8">
        <h2 className="text-2xl font-semibold mb-2">PWA Setup</h2>
        <div className="space-y-5">
          <CardCode
            card={`npm create vite@latest my-pwa-app --template react`}
          />
          <span className="text-gray-900 italic text-sm">
            # This create React project
          </span>

          <CardCode
            card={`cd my-pwa-app
npm install`}
          />

          <CardCode card={`npm install vite-plugin-pwa --save-dev`} />
          <span className="text-gray-900 italic text-sm">
            # This install PWA plugin for @React-Vite on your project
          </span>

          <CardCode
            card={`import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { VitePWA } from 'vite-plugin-pwa';

export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      registerType: 'autoUpdate',
      manifest: {
        name: 'My PWA App',
        short_name: 'PWA App',
        description: 'My awesome Progressive Web App!',
        theme_color: '#ffffff',
        icons: [
          {
            src: 'icon-192x192.png',
            sizes: '192x192',
            type: 'image/png',
          },
          {
            src: 'icon-256x256.png',
            sizes: '256x256',
            type: 'image/png',
          },
          {
            src: 'icon-384x384.png',
            sizes: '384x384',
            type: 'image/png',
          },
          {
            src: 'icon-512x512.png',
            sizes: '512x512',
            type: 'image/png',
          },
        ],
      },
    }),
  ],
});`}
          />

          <span className="text-gray-900 italic text-sm">
            # Modify <span className="font-semibold">viteconfig.js </span>{" "}
            *//Just copy the code
          </span>

          <CardCode
            card={`import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './index.css';
import { registerSW } from 'virtual:pwa-register';

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

// Register the service worker
const updateSW = registerSW({
  onNeedRefresh() {
    // Optionally handle when a new service worker is installed
    // For example, show a "refresh" button to the user
  },
  onOfflineReady() {
    // Optionally handle when the app is ready to work offline
  },
});
`}
          />
          <span className="text-gray-900 italic text-sm">
            # Also modify{" "}
            <span className="font-semibold">main.js or index.js </span>
          </span>
          <CardCode
            card={`{
  "name": "My PWA App",
  "short_name": "PWA App",
  "description": "My awesome Progressive Web App!",
  "start_url": "/",
  "display": "standalone",
  "background_color": "#ffffff",
  "theme_color": "#ffffff",
  "icons": [
    {
      "src": "/icon-192x192.png",
      "sizes": "192x192",
      "type": "image/png"
    },
    {
      "src": "/icon-256x256.png",
      "sizes": "256x256",
      "type": "image/png"
    },
    {
      "src": "/icon-384x384.png",
      "sizes": "384x384",
      "type": "image/png"
    },
    {
      "src": "/icon-512x512.png",
      "sizes": "512x512",
      "type": "image/png"
    }
  ]
}`}
          />

          <span className="text-gray-900 italic text-sm">
            # Add <span className="font-semibold">manifest.json</span> file in
            your public directory
          </span>

          <CardCode card={`npm run build`} />
          <span className="text-gray-900 italic text-sm">
            # This will create a <span className="font-semibold">dist</span>{" "}
            folder in your project <br />{" "}
            <span className="font-semibold">dist</span> - This is the directory
            where your production build files are located. The dist folder is
            typically generated by running{" "}
            <span className="font-semibold text-base">npm run build</span> and
            contains the optimized and minified assets ready for deployment.
          </span>

          <CardCode
            card={`npm install -g serve
serve -s dist`}
          />
          <span className="text-gray-900 italic text-sm">
            <span className="font-semibold">`npm install -g serve` -</span> This
            command installs the serve package globally on your system. <br />
            <span className="font-semibold">`serve -s dist` -</span> This
            command uses the serve package to serve static files from a
            specified directory.{" "}
          </span>
        </div>
      </div>
    </div>
  );
}

export default pwa;
